using System;
using System.Linq;
using MokomoGamesLib.Runtime.Audio.ResourceMasterTable.AutoGenerated;
using MokomoGamesLib.Runtime.GameConfig;

namespace MokomoGamesLib.Runtime.Audio
{
    public static class Service
    {
        public static void PlayOneShot(AudioManager audioManager, SoundName soundName, GameConfigManager gameConfigManager)
        {
            if (gameConfigManager.Config.IsMute) return;

            var speakerPresenter = audioManager.GetSpeaker(soundName);
            speakerPresenter.PlayOneShot(null);
        }

        public static void Stop(AudioManager audioManager, SoundName soundName)
        {
            var speakerPresenter = audioManager.GetSpeaker(soundName);
            speakerPresenter.Stop();
        }

        public static void StopAll(AudioManager audioManager)
        {
            var soundNames = Enum.GetValues(typeof(SoundName)).Cast<SoundName>().ToList();
            foreach (var soundName in soundNames) Stop(audioManager, soundName);
        }
    }
}