using MokomoGamesLib.Runtime.Audio;
using MokomoGamesLib.Runtime.Audio.ResourceMasterTable.AutoGenerated;
using MokomoGamesLib.Runtime.GameConfigs;
using UnityEngine;
using UnityEngine.UI;

namespace MokomoGamesLib.Runtime.UI
{
    public class PlayButtonSoundProcess : MonoBehaviour
    {
        [SerializeField] private Button button;
        [SerializeField] private SoundName soundName;

        private void Start()
        {
            button.onClick.AddListener(() =>
            {
                Service.PlayOneShot(
                    soundName,
                    FindObjectOfType<AudioManager>(),
                    FindObjectOfType<GameConfigManager>()
                );
            });
        }
    }
}