using System;
using MokomoGamesLib.Runtime.Audio.ResourceMasterTable.AutoGenerated;
using UnityEngine;

namespace MokomoGamesLib.Runtime.Audio.Speakers
{
    public class Speaker
    {
        private float _volume;
        public Speaker(SoundName soundName, AudioClip audioClip, float volume)
        {
            SoundName = soundName;
            AudioClip = audioClip;
            Volume = volume;
        }

        public float Volume
        {
            get => _volume;
            set
            {
                _volume = value;
                OnChangedVolume?.Invoke(this);
            }
        }
        public SoundName SoundName { get; }
        public AudioClip AudioClip { get; }
        public event Action<Speaker> OnChangedVolume;
    }
}