using System.Collections.Generic;
using System.Linq;
using MokomoGamesLib.Runtime.Audio.ResourceMasterTable.AutoGenerated;
using MokomoGamesLib.Runtime.Audio.Speakers;
using UnityEngine;

namespace MokomoGamesLib.Runtime.Audio.ResourceMasterTable
{
    public class MasterTable : MonoBehaviour
    {
        [SerializeField] private List<Record> records = new();

        public Record Find(SoundName soundName)
        {
            var record = records.FirstOrDefault(x => x.SoundName == soundName);
            if (record != null) return record;

            Debug.LogError($"{soundName.ToString()}にひもづくマスターデータが存在しません。");
            return null;
        }
    }
}