using System;
using MokomoGamesLib.Runtime.Audio.ResourceMasterTable.AutoGenerated;
using UnityEngine;

namespace MokomoGamesLib.Runtime.Audio.ResourceMasterTable
{
    [Serializable]
    [CreateAssetMenu(
        fileName = "AudioResourceMasterRecord",
        menuName = "MokomoGames/Audio/オーディオリソース設定ファイルの作成")
    ]
    public class Record : ScriptableObject
    {
        // TODO: SoundNameは自動生成を行うように
        [SerializeField] private SoundName soundName;
        [SerializeField] private AudioClip audioClip;
        [SerializeField] private float sourceVolume = 1.0f;

        public SoundName SoundName => soundName;

        public AudioClip AudioClip => audioClip;

        public float SourceVolume => sourceVolume;
    }
}